name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # latest v4 runs on Node 24 by default

      - name: Set up Python
        uses: actions/setup-python@v5  # latest v5 runs on Node 24 by default
        with:
          python-version: '3.11.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright

      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps

      - name: Run Playwright tests
        run: pytest -v